#!/bin/sh
set -e

case "$1" in
  configure)
    if ! getent passwd postinod >/dev/null; then
      adduser --system --group --no-create-home --quiet \
              --home /nonexistent --shell /usr/sbin/nologin postinod
    fi
    install -d -o root -g root -m 0755 /etc/postino
    if [ -x /bin/systemctl ]; then
      systemctl daemon-reload || true
    fi
    ;;
esac

#DEBHELPER#
exit 0
